# Generated by Django 5.1.3 on 2024-11-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
